services:
  - type: web
    name: inventory-tracker
    env: node
    buildCommand: ./render-build.sh
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true
    healthCheckPath: /api/health
    publishDirectory: dist
    disk:
      name: inventory-data
      mountPath: /data
      sizeGB: 1